LIST(APPEND CMAKE_MODULE_PATH "${CMAKE_SOURCE_DIR}/cmake/CMakeModules/")

IF(CMAKE_COMPILER_IS_GNUCC)
    FIND_PACKAGE(PkgConfig REQUIRED)
    FIND_PACKAGE(Check REQUIRED)
    FIND_PACKAGE(Valgrind REQUIRED)
ENDIF()